### ISSUE TITLE
dev: Calldata update process

### ISSUE THREAD

**Issue by JordyRo1** [astraly-labs/pragma-monorepo#56]
# Data Processing and User Interaction Flow

## System Process Flow
1. **Hyperlane Dispatch Event**
   - The process begins when Hyperlane triggers a `dispatch` action
   - This generates a DispatchEvent containing a message with metadata and a list of update data

2. **Message Processing**
   - A unique message ID is derived from the dispatched message
   - The message ID is used to find corresponding entries in the checkpoint storage
   - When a match is found, the system stores:
     - HashMap<FeedId, UpdateData>

## User Interaction Flow
1. Users interact with the system by calling the API endpoint with a specific feed ID
2. The system retrieves and returns the associated information, which is already stored and indexed by feed ID

## Implementation Checklist
1. [x] Develop a function to convert messages into message IDs
2. [x] Create a batch of retrieve events
4. [x] Implement a function to verify message ID correspondence in checkpoint storage for each batched message
5. [ ] Create a function to:
   - Parse update information
   - Store data in the appropriate format

**Comment by EvolveArt** [comment]
![image](https://github.com/user-attachments/assets/47ef544a-a528-4085-8e57-3f9973f15cec)
